### ISSUE TITLE
Web 0주차 - HTML, CSS, JS

### ISSUE THREAD

**Issue by SeyeonJang** [SeyeonJang/UMC-6th-Web#1]
### 💻 To-do
- [x] HTML 기초 & React 배우기
- [x] HTML 태그
- [x] CSS 셀렉터, 기초 이론
- [x] CSS 레이아웃
- [x] CSS Flexbox
- [x] JavaScript 역사 알기
<br>

### 📸 ScreenShot
<img width="130" alt="image" src="https://github.com/SeyeonJang/UMC-6th-Web/assets/47477205/88dd938e-a7b3-4460-a6d5-14a81b92d0ad">
<img width="150" alt="image" src="https://github.com/SeyeonJang/UMC-6th-Web/assets/47477205/ff9f8e0d-19fa-46a7-ac13-cfddb8bac8b7">
<img width="150" alt="image" src="https://github.com/SeyeonJang/UMC-6th-Web/assets/47477205/28993443-acc4-4252-b3f4-fe60487b1bfe">
<img width="100" alt="image" src="https://github.com/SeyeonJang/UMC-6th-Web/assets/47477205/b9787946-4846-4cb2-8320-c3e7c7ded1b2">
<img width="90%" alt="image" src="https://github.com/SeyeonJang/UMC-6th-Web/assets/47477205/02b1071e-bddc-4ba9-ae66-f1769e8f7109">

<br><br>

### 😊 참고 영상
- [HTML 기초, React 할때 꼭 필요한 팁! 쉽다고 무시하면 안돼요 | 프론트엔드 개발자 입문편: HTML, CSS, Javascript](https://youtu.be/i0FN-OwJ7QI?feature=shared)
- [HTML 태그 완성, 웹 포트폴리오 만들기 전에 꼭 보세요 | 프론트엔드 개발자 입문편: HTML, CSS, Javascript](https://youtu.be/OoA70D2TE0A?feature=shared)
- [CSS 셀렉터, 기초 이론 정리. 포트폴리오 만드는 날까지! | 프론트엔드 개발자 입문편: HTML, CSS, Javascript](https://youtu.be/gGebK7lWnCk?feature=shared)
- [CSS 레이아웃 정리 display, position 완성 | 프론트엔드 개발자 입문편: HTML, CSS, Javascript](https://youtu.be/jWh3IbgMUPI?feature=shared)
- [CSS Flexbox 완전 정리. 포트폴리오 만드는 날까지! | 프론트엔드 개발자 입문편: HTML, CSS, Javascript](https://youtu.be/7neASrWEFEM?feature=shared)
- [자바스크립트 배우기전 꼭 봐야할 영상 | 자바스크립트의 역사와 현재 그리고 미래 (JavaScript, ECMAScript, JQuery, Babel, Node.js)](https://youtu.be/wcsVjmHrUQg?feature=shared)
