### ISSUE TITLE
Web 3주차 실습 - 실제 API로 영화 사이트 만들기

### ISSUE THREAD

**Issue by SeyeonJang** [SeyeonJang/UMC-6th-Web#10]
### 💻 To-do
**영화 사이트 만들기**
- [x] TMDB 실제 영화 데이터 불러오기 
- [x] Styled-Components로 변경
- [x] react-router-dom을 활용해서 Navbar와 Footer를 고정시키고, 가운데의 영화 포스터 내용들만 변경되도록 만들기
- 다양한 페이지 컴포넌트 만들고 라우팅 설정하기
  - [x] MainPage.jsx
  - [x] PopularPage.jsx
  - [x] NowPlayingPage.jsx
  - [x] TopRatedPage.jsx
  - [x] UpComing.jsx
- [x] MainPage에서, ‘환영합니다’ 텍스트의 Banner 컴포넌트 보여주기

**Navbar**
- [x] Navbar(상단바)에서 Popular를 누르면 popular 페이지로 이동 후, 실제 Popular 영화 데이터를 불러오기
- [x] Navbar(상단바)에서 Now Playing을 누르면 nowplaying 페이지로 이동 후, 실제 NowPlaying 영화 데이터를 불러오기
- [x] Navbar(상단바)에서 Top Rated를 누르면 toprated 페이지로 이동 후, 실제 TopRated 영화 데이터를 불러오기
- [x] Navbar(상단바)에서 Up Coming을 누르면 upcoming 페이지로 이동 후, 실제 UpComing 영화 데이터를 불러오기
- [x] Navbar(상단바)에서 로고(UMC Movie)를 누르면 홈페이지로 이동 후, Popular 영화 데이터를 불러오기
- [x] 컴포넌트 재사용을 했는지 확인하기
- [x] Navbar(상단바) 메뉴 hover시 살짝 커지는 효과, 커서 변경 스타일링 해보기
<br>

### 영화 사이트

https://github.com/SeyeonJang/UMC-6th-Web/assets/47477205/284c64bc-5726-4fc8-8d0d-9796b1d1f576

https://github.com/SeyeonJang/UMC-6th-Web/assets/47477205/862cd62d-e133-4bb7-b5d1-fb912adab8de

https://github.com/SeyeonJang/UMC-6th-Web/assets/47477205/ea47f7c2-d229-47c8-91a1-1091087bf52a

<br><br>

### 😊 참고한 내용
- [[setting] React 컴포넌트 분리와 폴더 구조화](https://ventos06.tistory.com/4)
- [BEM 방법론 정리 (네이밍 규칙)](https://velog.io/@nemo/bem)
- [React 개발환경 세팅하기 - 2. React Router 설치](https://velog.io/@jungsw586/React-%EA%B0%9C%EB%B0%9C%ED%99%98%EA%B2%BD-%EC%84%B8%ED%8C%85%ED%95%98%EA%B8%B0-2.-React-Router-%EC%84%A4%EC%B9%98)
- [[React] 리액트 라우터(react-router-dom) 중첩 라우팅으로 하위페이지 연결하기 - nested routing, outlet](https://junvelee.tistory.com/36)
- [[HTML, CSS] div 요소를 전체화면으로 설정하기, 끝부분 적용안되는 문제, css reset](https://codingbroker.tistory.com/56)
