### ISSUE TITLE
Web 4주차 미션 - NavBar, MovieDetailPage, NotFoundPage

### ISSUE THREAD

**Issue by SeyeonJang** [SeyeonJang/UMC-6th-Web#13]
### 💻 To-do

**NavBar**
- [x] 로그인 버튼, 클릭 시 로그아웃으로 텍스트가 변경
- [x] 반대로, 로그아웃 버튼 클릭 시 로그인 텍스트로 변경
- [x] 미션의 모든 컴포넌트나 페이지를 스타일링 할 때 styled-components 이용
- [x] 클릭 시 해당 경로로 이동 후, 이동한 페이지의 navbar 텍스트를 노란색으로 표기

**MovieDetailPage**
- [x] 라우팅 경로를 /movie/영어로된 영화 이름 으로 설정 (ex. movie/SpiderMan)
- [x] 개별 영화 상세 정보 Get
- [x] 평점을 단순 소수점 값이 아닌 영화 상세페이지에서는, ⭐️ 으로 계산
- [x] 줄거리가 없는 경우, 유저들에게 줄거리가 없다고 알림

**NotFoundPage**
- [x] 잘못된 경로로 갔을 때 NotFound 페이지
- [x] 에러 페이지를 구현해보고, 사용자가 다시 메인 페이지로 이동할 수 있게 기능 제공
<br>

### NavBar

https://github.com/SeyeonJang/UMC-6th-Web/assets/47477205/00f17408-fe97-4172-b1c6-00a1df721b6a

### MoveDetailPage

https://github.com/SeyeonJang/UMC-6th-Web/assets/47477205/a9023416-fd3e-4894-9ce2-20a77b5a53fd

### NotFoundPage

https://github.com/SeyeonJang/UMC-6th-Web/assets/47477205/798f3f0b-f973-4f06-8da5-f65466cd461f

<br>
