### ISSUE TITLE
Web 5주차 미션1 - 회원가입 유효성 검사

### ISSUE THREAD

**Issue by SeyeonJang** [SeyeonJang/UMC-6th-Web#17]
### 💻 To-do

**라우팅**
- [x] 기존의 로그인, 로그아웃 버튼을 지우고 회원가입 버튼으로 변경
- [x] Navbar에 있는 회원가입 버튼을 클릭하면 `/signup` 페이지로 이동

**이름**
- [x] 이름은 문자열이어야 합니다.
- [x] 반드시, 이름을 사용자로부터 입력받아야 합니다. (입력하지 않았을 시 제출하기 폼 버튼 비활성화)

**이메일**
- [x] 이메일은 문자열이어야 합니다.
- [x] 이메일 양식을 맞춰주어야 합니다. ‘@’가 있어야합니다.
- [x] 반드시, 이메일을 사용자로부터 입력을 받아야 합니다. (입력하지 않았을 시 제출하기 폼 버튼 비활성화)

**나이**
- [x] 나이는 숫자를 입력받아야 합니다. (문자열을 입력할 시 해당 에러 메시지 출력)
- [x] 나이는 음수가 될 수 없습니다. (음수 값을 입력할 시 해당 에러 메시지 출력)
- [x] 나이는 소수가 될 수 없습니다. (소수 값을 입력할 시 해당 에러 메시지 출력)
- [x] 우리 영화 사이트는 19살 이상만 가입이 가능합니다. (19살 미만의 숫자를 입력할 시 해당하는 에러 메시지 출력)
- [x] 반드시, 나이를 사용자로부터 입력을 받아야 합니다. (입력하지 않았을 시 제출하기 폼 버튼 비활성화)

**비밀번호**
- [x] 비밀번호는 문자열이어야 합니다.
- [x] 비밀번호는 최소 4자리 이상이어야 합니다. (4자리 이하일 때 해당 에러 메시지 출력)
- [x] 비밀번호는 최대 12자리까지 가능합니다. (13자리 입력 시, 해당 에러 메시지 출력)
- [x] 영어, 숫자, 특수문자를 모두 조합해서 비밀번호를 작성해야 합니다. (모두 조합하지 않았을 때, 해당 에러 메시지가 출력됩니다.)
- [x] 반드시, 비밀번호를 사용자로부터 입력을 받아야 합니다. (입력하지 않았을 시 제출하기 폼 버튼 비활성화) 

**비밀번호 확인**
- [x]  비밀번호 확인은 문자열이어야 합니다.
- [x]  4번에서 작성한 비밀번호와 5번에서 작성한 비밀번호가 같은지 확인하고, 동일하지 않다면 해당 에러 메시지가 출력됩니다.
- [x]  반드시, 비밀번호 확인을 사용자로부터 받아야 합니다. (입력하지 않았을 시 제출하기 폼 버튼 비활성화)

**공통**
모든, input창에 해당하는 `**에러 메세지는 실시간으로 변경**`이 되어야 합니다. 아래 예시는 이메일인 경우입니다.
```jsx
// 이메일 기준
dyd -> 이메일 양식에 맞지 않습니다. (에러메시지 출력)
dydals3440@gmail.com -> 에러메시지 제거 (이메일 양식에 맞으므로)
```
- [x] 에러 메시지가 실시간으로 변동되고, 반영되는지 확인
- [x]  `유효성 로직이 통과했을 때만, 폼 데이터가 전달`되는지 `console.log` 통해 확인
- [x]  모든 스타일링은 `styled-components`를 활용

**제출하기 클릭 시**
- [x]  회원가입 Validation이 모두 통과했을 때만, 제출하기 버튼 클릭 시 `form-data`를 전송해 줄 수 있습니다. `console.log` 를 통해 `유효성 검사가 통과했을 때만`, 우리가 입력한 회원가입 정보가 제대로 전송되는지 확인해 주세요!
- [x]  모든 회원가입 Validation을 통과했을 경우, 로그인페이지로 이동해주세요.

<br>

### 📸 ScreenShot
![스크린샷 2024-05-10 오전 12 23 43](https://github.com/SeyeonJang/UMC-6th-Web/assets/47477205/6305a661-3389-4f44-b6f3-b941252f493d)
![스크린샷 2024-05-10 오전 12 24 18](https://github.com/SeyeonJang/UMC-6th-Web/assets/47477205/edd1fd19-69c6-46f1-89d1-85abc1a5c6c9)
![스크린샷 2024-05-10 오전 12 24 42](https://github.com/SeyeonJang/UMC-6th-Web/assets/47477205/ef5aaacb-1919-48ce-8437-eb13b30822be)

<br>
