### ISSUE TITLE
Web 5주차 미션2 - 영화 찾기 기능 구현

### ISSUE THREAD

**Issue by SeyeonJang** [SeyeonJang/UMC-6th-Web#18]
### 💻 To-do
- [x]  `MainPage(’/’)` 경로에 검색 기능을 추가
- [x]  검색어가 없을 때는 검색 결과 창이 활성화되지 않게 만들기
- [x]  TMDB 공식 문서 `Search 부분 정독 후` 사용법 익히기 (아래 링크 참고)
[Search - Movies](https://developer.themoviedb.org/reference/search-movie)
- [x]  입력한 키워드에 해당하는 `영화 데이터 화면에 출력`하기
- [x]  `Scrollbar`도 멋있게 스타일링 해주기
- [x]  검색 목록이 나오는 부분도 멋있게 스타일링 해주기
<br>

### 📸 ScreenShot

https://github.com/SeyeonJang/UMC-6th-Web/assets/47477205/a6450b6b-84f4-45a9-af5f-663c83458d72

![스크린샷 2024-05-12 오후 1 45 44](https://github.com/SeyeonJang/UMC-6th-Web/assets/47477205/d812e1ff-f283-409a-82c5-3ec7ffab7e6a)
![스크린샷 2024-05-12 오후 1 46 19](https://github.com/SeyeonJang/UMC-6th-Web/assets/47477205/aa2e73b0-449c-46f5-9435-f12101df8f58)
