### ISSUE TITLE
Web 1주차 실습 - 카운터, 모달

### ISSUE THREAD

**Issue by SeyeonJang** [SeyeonJang/UMC-6th-Web#2]
### 💻 To-do

**카운터 만들기**
- [x] UI 만들기
- [x] DOM 선택하기
- [x] 버튼 클릭 이벤트 설정하기
- [x] 카운터 구현하기

**모달 만들기**
- [x] UI 만들기
- [x] 모달 UI 만들기
- [x] 모달 CSS 짜기
- [x] display 스타일을 사용하여 모달 열고 닫기
- [x] 버튼 클릭 이벤트 설정하기
<br>

### 카운터
<video src="https://github.com/SeyeonJang/UMC-6th-Web/assets/47477205/e7417f3f-001d-4cd7-8c8e-c593447b59b8" autoplay muted loop></video>
### 모달
<video src="https://github.com/SeyeonJang/UMC-6th-Web/assets/47477205/d454e783-a1b6-4210-bef7-97f97b2ea53d" autoplay muted loop></video>

<br><br>

### 😊 참고한 내용
- 모달 창 (https://velog.io/@bami/%EB%AA%A8%EB%8B%AC-%EC%B0%BD-Modal)
- [CSS] 좌측 정렬에서 마지막만 우측 정렬하는 법 (https://smthousand.tistory.com/28)
