### ISSUE TITLE
Web 6주차 미션2 - 로딩처리 & Dynamic Routing을 활용한 API 요청

### ISSUE THREAD

**Issue by SeyeonJang** [SeyeonJang/UMC-6th-Web#22]
### 💻 To-do
- [x]  영화 검색 후, 영화 클릭 시 해당 영화에 대한 상세페이지로 이동
- [x]  영화 검색 완료 이전에 `데이터를 받아오는 중입니다.` 문구가 보이게 하기
- [x]  기존에 `useLocation` / `useNavigation` 방식으로 했을 경우, `http://localhost:5173/movie/영화제목` 이런 식으로 URL이 설정되어있는 것을 [`http://localhost:5173/movie/](http://localhost:5173/movie/968051)영화ID`로 라우팅을 변경
- [x]  영화, 상세 페이지 정보를 `axios / fetch` 통신을 활용하여 받아오기 
- [x]  받아온 상세 페이지 정보를 활용하여, `**영화 상세 페이지를 멋있게 디자인**`
- [x]  해당 영화의 출연진, 감독진 정보 또한 `TMDB API Reference`를 참고하여 `axios / fetch` 통신을 활용하여 받아오기
- [x]  영화의 출연진, 감독진 이미지 정보가 없을 경우, 아래 src 주소를 활용해서 `이미지 없음을 표기`
    - NO IMAGE src address
  
        ```tsx
        https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSz7ztleRwzXhFdiwBYqZ8cib9RvEsukVVUS3niN1YQ&s
        ```
- [x]  모든 스타일링은 기존의  `styled-components` 방식을 유지하면서 개발 진행

<br>

### 📸 ScreenShot

https://github.com/SeyeonJang/UMC-6th-Web/assets/47477205/7bf2cbef-b50a-430f-b5e8-432b9ef12d6f
