### ISSUE TITLE
Web 7주차 미션1 - 영화 페이지 개선

### ISSUE THREAD

**Issue by SeyeonJang** [SeyeonJang/UMC-6th-Web#25]
### 💻 To-do
**회원가입 페이지**
- [x]  회원가입 input 요소를 `이름, 아이디, 이메일, 나이, 비밀번호, 비밀번호 확인 총 6칸`이 되도록 변경
- [x]  아래에 이미 아이디가 있는 경우, 로그인 페이지로 이동할 수 있도록 처리

**로그인 페이지**
- [x]  아이디 입력칸은 필수적으로 입력 & 문자열만 입력, 그렇지 않을 경우 **`‘아이디를 입력해 주세요’`**라는 에러 메시지 띄우기
- [x]  비밀번호 입력칸은 필수적으로 입력, 기존 회원가입 때 사용한 유효성 검사 로직과 에러 메시지를 그대로 사용
- [x]  Navbar에 로그인 페이지로 라우팅할 수 있도록 버튼 추가

<br>

### 📸 ScreenShot
<img width="1510" alt="image" src="https://github.com/SeyeonJang/UMC-6th-Web/assets/47477205/c76263f7-006a-400e-9db2-3c8e21bf94c9">
<img width="1512" alt="image" src="https://github.com/SeyeonJang/UMC-6th-Web/assets/47477205/2ec1f7a7-9574-4d61-82f1-1f76dedaf64f">
<img width="1512" alt="image" src="https://github.com/SeyeonJang/UMC-6th-Web/assets/47477205/29773af6-6db7-4797-bbde-58993a897641">
