### ISSUE TITLE
Web 7주차 미션2 - Pagination & Infinite Scroll

### ISSUE THREAD

**Issue by SeyeonJang** [SeyeonJang/UMC-6th-Web#26]
### 💻 To-do
**Popular 페이지**
- [x]  `Pagination` 구현해보기
- [x]  1 페이지보다 이전 페이지는 갈 수 없기에 버튼 색상을 다르게 해서 유저에게 더 이상 해당 버튼은 클릭할 수 없다는 것을 알려주도록 UI/UX 개선
- [x]  가운데에는 현재 내가 몇 페이지에 있는지 알 수 있도록 설정
- [x]  이전 페이지를 누르면 이전 페이지 정보, 다음 페이지를 누르면 다음 페이지 정보가 보이도록 구현

**NowPlaying 페이지**
- [x]  `Infinite Scroll` 구현
- [x]  `Loading Spinner 컴포넌트`를 활용해서 `Infinite Scroll`시, 데이터를 받아오는 중일 때 `Loading Spinner`가 보이게 처리
        
<br>

### 📸 ScreenShot

https://github.com/SeyeonJang/UMC-6th-Web/assets/47477205/7d51fadf-fc74-45f1-a923-c3e3555c8251

https://github.com/SeyeonJang/UMC-6th-Web/assets/47477205/e4096e07-d73b-43ac-8541-6724fdaf75fa
