### ISSUE TITLE
Web 7주차 미션3 - 회원가입 (API 토큰)

### ISSUE THREAD

**Issue by SeyeonJang** [SeyeonJang/UMC-6th-Web#27]
### 💻 To-do
**회원가입 요청**
[가상 백엔드 서버 API & 명세서](https://github.com/dydals3440/UMC-5th-SMUFLIX-BE/tree/main)
- [x]  `백엔드 서버를 본인 레포에 Fork 후, git clone` 하신 후 `npm install → npm start`
- [x]  우리가 만든 `validation 규격에 맞추어서 회원가입을 진행` (이때, 프론트에서도 validation에 맞지 않는다면 **formData가 전송되지 않게 처리**)
- [x]  서버를 실행한 후, 깃헙 README.md에 있는 API 명세서에 알맞게 데이터 요청을 해서 회원가입 진행 `**(경로: http://localhost:8080/auth/signup)**`
- [x]  정상적으로 회원가입이 되었다면, alert를 통해 회원가입이 정상적으로 처리되었다고 문구 보여주기
- [x]  사용자가 바로 로그인할 수 있도록 로그인 페이지로 이동시키기 `(경로 : /login)`
        
**로그인**
- [x]  본인이 `회원가입 요청한 아이디와 비밀번호를 활용해서 로그인을 진행`
- [x]  `로그인 요청 주소는 API 명세서를 통해 확인`
- [x]  정상적으로 로그인이 되었다면 `메인 페이지(경로: ‘/’)`로 이동
- [x]  로그인 시 받는 `토큰을 로컬스토리지에 저장`
- [x]  페이지를 이동하더라도 계속 로그인 상태가 유지되게 처리
- [x]  토큰을 따로 보관한 후, API 명세서를 확인해 보시면 토큰을 활용하여 로그인 한 유저의 이름을 받아온 후, 배너에 `name님 환영합니다.` 를 표기
- [x]  바로 유저 데이터를 못 받아오므로, 데이터를 받아올 때까지 중간에 `배너에 로딩 중…`이라는 배너가 보이도록 설정

**Navbar**
1. 로그인 된 상태일 때
- [x]  Navbar에 `로그아웃 버튼만 보이게 설정`
2. 로그아웃 된 상태일 때
- [x]  토큰 제거
- [x]  로그인 버튼을 상단 바에 보이게 하기 `(경로: /login)`
- [x]  회원가입 버튼을 상단 바에 보이게 하기`(경로: /signup)`
- [ ]  배너는 `로그아웃 시 환영합니다 문구만 보이도록 설정`

<br>

### 📸 ScreenShot

![스크린샷 2024-05-28 오전 12 21 37](https://github.com/SeyeonJang/UMC-6th-Web/assets/47477205/7b0fdcd5-7ffd-483d-901d-d9f9a72f1b64)

![image](https://github.com/SeyeonJang/UMC-6th-Web/assets/47477205/b2661448-22e4-4e20-a396-b33f4b6acf45)
