### ISSUE TITLE
Web 8주차 미션1 - 영화사이트를 반응형으로 개선

### ISSUE THREAD

**Issue by SeyeonJang** [SeyeonJang/UMC-6th-Web#29]
### 💻 To-do
**각 페이지 반응형 구현하기**
- [x]  `메인 페이지`의 모든 컴포넌트가 깨지지 않도록 반응형 구현
- [x]  `영화 리스트 페이지`의 모든 컴포넌트가 깨지지 않도록 반응형 구현
- [x]  `회원가입 페이지`의 모든 컴포넌트가 깨지지 않도록 반응형 구현
- [x]  `로그인 페이지`의 모든 컴포넌트가 깨지지 않도록 반응형 구현
- [x]  `영화 상세 페이지`의 모든 컴포넌트가 깨지지 않도록 반응형 구현
<br>

### 📸 ScreenShot

https://github.com/SeyeonJang/UMC-6th-Web/assets/47477205/910a6198-fa9b-4411-bdad-851983601667

https://github.com/SeyeonJang/UMC-6th-Web/assets/47477205/cdc5b208-6a32-4f8b-84ac-fd7e69999a1d

https://github.com/SeyeonJang/UMC-6th-Web/assets/47477205/dd0db090-b12b-4b01-89cc-d4e9709c5383
