### ISSUE TITLE
Web 1주차 미션 - 회원가입 Validation, Todo List(CRUD)

### ISSUE THREAD

**Issue by SeyeonJang** [SeyeonJang/UMC-6th-Web#3]
### 💻 To-do

**회원가입 Validation**
- [x] UI 만들기
- [x] 모달 UI 만들기
- [x] CSS 만들기
- [x] 회원가입 Validation 코드
  - 이름 (문자열, 필수 항목)
  - 이메일 (문자열, @ 양식, 필수 항목)
  - 나이 (숫자, 음수 불가, 소수 불가, 19살 이상, 필수 항목)
  - 비밀번호 (문자열, 최소 4자리, 최대 12자리, 영어/숫자/특수문자 필수, 필수 항목)
  - 비밀번호 확인 (문자열, 비밀번호 확인, 필수 항목) 

**Todo List**
- [x] UI 만들기
- [x] CSS 만들기
- [x] input 컴포넌트에 내용을 작성하면 해야 할 일에 추가
- [x] 해야 할 일의 완료를 누르면 해당할 일이 해낸 일로 이동 
- [x] 해낸 일의 삭제를 누르면 삭제
<br>

### 회원가입
https://github.com/SeyeonJang/UMC-6th-Web/assets/47477205/7cc0a939-0512-401b-a4a4-2bd05d98b47e
### TodoList
https://github.com/SeyeonJang/UMC-6th-Web/assets/47477205/72a8f6d7-8c15-4a49-8253-4cffa590fbd4
