### ISSUE TITLE
Web 8주차 미션2 - SideBar 만들기

### ISSUE THREAD

**Issue by SeyeonJang** [SeyeonJang/UMC-6th-Web#32]
### 💻 To-do
**SideBar**
- [x]  태블릿&모바일 환경일 때 `메뉴 아이콘`이 나타나고, 아이콘을 누르면 `Sidebar가 나타나도록` 구현
- [x]  Sidebar 안의 내용은 `navbar와 같게`구현
- [x]  Sidebar 안의 메뉴를 클릭하면 페이지 이동과 동시에 `Sidebar가 닫혀야` 함
- [x]  Sidebar가 PC 환경일 때는 나타나지 않고 navbar가 나타나도록 설정
- [x]  가능하다면 Sidebar가 나타나고 사라질 때, 움직이는 애니메이션 구현
<br>

### 📸 ScreenShot

https://github.com/SeyeonJang/UMC-6th-Web/assets/47477205/5aea5b87-65c7-4659-94ea-021fdc7f33f3

https://github.com/SeyeonJang/UMC-6th-Web/assets/47477205/f0dfd1c6-970f-445b-9aca-b18d903b7861
