### ISSUE TITLE
Web 9주차 미션 - Redux-toolkit을 활용한 PlayList 만들기

### ISSUE THREAD

**Issue by SeyeonJang** [SeyeonJang/UMC-6th-Web#36]
### 💻 To-do
**redux-toolkit을 활용한 음원 장바구니**
- [x]  **기본 세팅** - 아래의 Mock-Data를, `constants 폴더에 별도로, 관리`해서 사용
    - 음반 정보 JSON 파일 (`cartItems.js`)
    - 아이콘 파일 (쇼핑 카트 아이콘, 수량 증가 & 감소 아이콘) (ìcon.js`)
- [x]  모든 스타일링을 `styled-components`를 활용
- [x]  전역 상태 관리 라이브러리인 `redux-toolkit`  활용
- [x]  `redux-toolkit`를 사용하기 위해 `Provider`를 연결
- [x]  `configureStore`를 활용해 중앙 저장소 만들기
- [x]  cart에 관한 상태 - `cartSlice`를 만들고 중앙 저장소에 연결
- [x]  `음반수량 증가`시 해당하는 음반의 수량이 증가되게 `action` 함수 만들기 (**`increase action 기능 구현`**)
- [x]  `음반수량 감소`시 해당하는 음반의 수량이 증가되게 `action` 함수 만들기 (**`decrease action 기능 구현`**)
- [x]  음반 수량이 1보다 작아질 수 없지 않을까요? `1보다 작아진다면, 장바구니 목록에서 자동으로 제거`되게 만들기 (**`removeItem action 기능 구현`**)
- [x]  `장바구니 초기화` 버튼을 누르면 선택한 음반들이 다 제거되도록 화면 구성 (**`clearCart action 기능 구현`**)
- [x]  전체 금액이 얼마인지, 장바구니에 담고 있는 전체 수량이 몇 개인지, 계산해주는 action 함수를 만들기 (**`calculateTotals action 기능 구현`**)
<br>

### 📸 ScreenShot

https://github.com/SeyeonJang/UMC-6th-Web/assets/47477205/5e2a3b7e-fae3-4d3c-8e47-d0cf79c6d5c1

https://github.com/SeyeonJang/UMC-6th-Web/assets/47477205/9e00762e-1294-4bab-b151-22554f0120f0
