### ISSUE TITLE
Web 10주차 미션 - Playlist에 API 연결하기

### ISSUE THREAD

**Issue by SeyeonJang** [SeyeonJang/UMC-6th-Web#39]
### 💻 To-do
**BE 서버 fork 후 API 연결**
- [x]  [서버 repository](https://github.com/dydals3440/SMUMC-ReduxToolkit-BE/tree/main)를 내 repository에 Fork후 clone
- [x]  `createAsyncThunk`를 활용해서, initialState의 cartItems를 mock-data가 아닌 서버 통신으로 받아올 수 있게 구현 **`(async) 활용`**
- [x]  try catch를 통해서 에러/예외사항 처리
- [x]  `extraReducers`를 활용하여 `Life Cycle` 작업 (`BuilderCallbackNotation`을 활용한 `pending`, `fulfilled`, `rejected` 처리)
- [x] 데이터를 받아오는 중일 때 '로딩 중'이라는 멘트와 Spinner가 나올 수 있도록 UI 추가
- [x] 서버의 응답 데이터가 없는 경로(json이 없는 경로)로 갔을 때, alert 창이 나오고 해당하는 payload의 에러가 보이게 작업

<br>

### 📸 ScreenShot
<img width="845" alt="image" src="https://github.com/SeyeonJang/UMC-6th-Web/assets/47477205/4d4e3ed5-40af-477a-9882-f5a3e7fddca3">
<img width="461" alt="image" src="https://github.com/SeyeonJang/UMC-6th-Web/assets/47477205/787bf217-e4ad-4d99-9163-96d43d3a536d">
