### ISSUE TITLE
Web 2주차 실습 - 카운터, 모달

### ISSUE THREAD

**Issue by SeyeonJang** [SeyeonJang/UMC-6th-Web#6]
### 💻 To-do
- [x] React 실습 환경 구축하기

**카운터 만들기**
- [x] UI 만들기
- [x] 카운터 상태 관리하기
- [x] 버튼 클릭 이벤트 설정하기
- [x] 카운터 구현하기

**모달 만들기**
- [x] UI 만들기
- [x] 모달 UI 만들기
- [x] 모달 CSS 짜기
- [x] 버튼 클릭 이벤트 부여
- [x] 버튼 클릭 이벤트, 상태 연결을 통해 모달 열고 닫는 기능 구현
<br>

### 카운터
https://github.com/SeyeonJang/UMC-6th-Web/assets/47477205/8672d34b-ce64-436d-8ee5-e389140c7ee2
### 모달
https://github.com/SeyeonJang/UMC-6th-Web/assets/47477205/01410542-6c82-4bee-a8bb-c515a1ece313

<br><br>

### 😊 참고한 내용
- [React 프로젝트 시작하기 w. Vite](https://www.heropy.dev/p/6iFzkBc)
- [[React]리액트의 폴더 구조](https://velog.io/@sisofiy626/React-%EB%A6%AC%EC%95%A1%ED%8A%B8%EC%9D%98-%ED%8F%B4%EB%8D%94-%EA%B5%AC%EC%A1%B0)
