### ISSUE TITLE
Web 2주차 미션 - Todo List, Movie Poster

### ISSUE THREAD

**Issue by SeyeonJang** [SeyeonJang/UMC-6th-Web#7]
### 💻 To-do

**Todo List**
- [x] UI 만들기
  - 제목
  - 해야 할 일 작성 칸
- [x] 컴포넌트 UI 생성
  - 해야 할 일 / 해낸 일 표시
- [x] CSS 만들기
- [x] input 컴포넌트에 내용을 작성하면 해야 할 일에 추가
- [x] 해야 할 일의 완료를 누르면 해당할 일이 해낸 일로 이동 
- [x] 해낸 일의 삭제를 누르면 삭제

**Movie Poster**
- [x] API 사용하기
- [x] API를 활용하여 영화 데이터를 불러와서 컴포넌트 분리한 UI 생성
- [x] 영화 개수만큼 컴포넌트 불러오기
- [x] 영화 상세 설명 컴포넌트 만들기
- [x] 마우스를 포스터 위에 올리지 않았을 때는 화면에서 상세 설명 컴포넌트가 보이지 않게 만들기
- [x] 마우스를 포스터 위에 올렸을 때만 화면에서 해당 컴포넌트가 보이게 만들기
<br>

### Todo List
https://github.com/SeyeonJang/UMC-6th-Web/assets/47477205/fcbf9882-26c2-41a6-a56f-7bbf35d5a403

### Movie Poster
https://github.com/SeyeonJang/UMC-6th-Web/assets/47477205/8b222005-d208-481a-9515-8169a1eb5f70

<br>
